/* ===== Shared data for Wayfare Travel ===== */

const DESTINATIONS = [
  {
    id: "bali",
    name: "Bali, Indonesia",
    category: "Beach",
    price: 75520,
    rating: 4.8,
    days: 6,
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=900&q=80",
    description: "Rice terraces, surf beaches and temple mornings on Indonesia's island of the gods.",
  },
  {
    id: "santorini",
    name: "Santorini, Greece",
    category: "Beach",
    price: 108360,
    rating: 4.9,
    days: 5,
    image: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=900&q=80",
    description: "Whitewashed cliff villages, caldera sunsets and slow Aegean ferry days.",
  },
  {
    id: "kyoto",
    name: "Kyoto, Japan",
    category: "Cultural",
    price: 130200,
    rating: 4.9,
    days: 7,
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=900&q=80",
    description: "Temple gardens, bamboo groves and kaiseki dinners in Japan's old capital.",
  },
  {
    id: "swiss-alps",
    name: "Swiss Alps, Switzerland",
    category: "Mountain",
    price: 149520,
    rating: 4.7,
    days: 6,
    image: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=900&q=80",
    description: "Glacier railways, alpine huts and lake towns beneath the Jungfrau ridge.",
  },
  {
    id: "marrakech",
    name: "Marrakech, Morocco",
    category: "Cultural",
    price: 62160,
    rating: 4.6,
    days: 5,
    image: "https://images.unsplash.com/photo-1597212618440-806262de4f6b?auto=format&fit=crop&w=900&q=80",
    description: "Souk bargaining, riad courtyards and a night crossing into the Agafay desert.",
  },
  {
    id: "serengeti",
    name: "Serengeti, Tanzania",
    category: "Wildlife",
    price: 205800,
    rating: 4.9,
    days: 8,
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=900&q=80",
    description: "Great Migration river crossings, tented camps and sunrise balloon flights.",
  },
  {
    id: "iceland",
    name: "Reykjavik, Iceland",
    category: "Adventure",
    price: 136080,
    rating: 4.8,
    days: 6,
    image: "https://images.unsplash.com/photo-1504829857797-ddff29c27927?auto=format&fit=crop&w=900&q=80",
    description: "Ice caves, black sand coastlines and aurora hunting on the Golden Circle.",
  },
  {
    id: "maldives",
    name: "Maldives",
    category: "Beach",
    price: 176400,
    rating: 4.9,
    days: 5,
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=900&q=80",
    description: "Overwater villas, house-reef snorkelling and seaplane hops across the atolls.",
  },
  {
    id: "patagonia",
    name: "Patagonia, Chile",
    category: "Adventure",
    price: 166320,
    rating: 4.7,
    days: 9,
    image: "https://images.unsplash.com/photo-1478827387698-1527781a4887?auto=format&fit=crop&w=900&q=80",
    description: "The W trek through Torres del Paine, guanaco plains and glacier lookouts.",
  },
  {
    id: "rome",
    name: "Rome, Italy",
    category: "Cultural",
    price: 82320,
    rating: 4.6,
    days: 5,
    image: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=900&q=80",
    description: "Forum walks, Trastevere trattorias and an early-entry Vatican morning.",
  },
  {
    id: "queenstown",
    name: "Queenstown, New Zealand",
    category: "Adventure",
    price: 157080,
    rating: 4.8,
    days: 8,
    image: "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?auto=format&fit=crop&w=900&q=80",
    description: "Fiord cruises, bungy bridges and Milford Sound day trips from Lake Wakatipu.",
  },
  {
    id: "banff",
    name: "Banff, Canada",
    category: "Mountain",
    price: 119280,
    rating: 4.7,
    days: 6,
    image: "https://images.unsplash.com/photo-1609825488888-3a766db05542?auto=format&fit=crop&w=900&q=80",
    description: "Turquoise lakes, the Icefields Parkway and gondola evenings above the valley.",
  },
];

const PACKAGES = [
  {
    id: "bali-escape",
    title: "Bali Island Escape",
    destinationId: "bali",
    location: "Ubud & Seminyak, Indonesia",
    category: "Beach",
    price: 75520,
    oldPrice: 1080,
    days: 6,
    nights: 5,
    groupSize: "Max 12 travellers",
    rating: 4.8,
    reviews: 214,
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1555400038-63f5ba517a47?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1604999565976-8913ad2ddb7c?auto=format&fit=crop&w=1200&q=80",
    ],
    summary:
      "Split your week between the rice-terrace calm of Ubud and the surf and sunset bars of Seminyak, with a private driver on call throughout.",
    includes: ["5 nights in 4-star resorts", "Daily breakfast", "Airport transfers", "Private driver for 4 days", "Mount Batur sunrise trek", "Ubud cooking class"],
    excludes: ["International flights", "Travel insurance", "Lunches and dinners", "Personal expenses"],
    itinerary: [
      { day: "Day 1", title: "Arrival in Denpasar", text: "Private transfer to Ubud, welcome dinner and a walk through the night market." },
      { day: "Day 2", title: "Rice terraces & temples", text: "Tegalalang terraces, Tirta Empul water temple and an afternoon spa session." },
      { day: "Day 3", title: "Mount Batur sunrise", text: "Pre-dawn trek to the summit, breakfast on the crater rim, hot springs after." },
      { day: "Day 4", title: "Cooking class & move to Seminyak", text: "Market tour and Balinese cooking class, then transfer to the coast." },
      { day: "Day 5", title: "Beach and surf day", text: "Beginner surf lesson, free afternoon and a sunset seafood dinner in Jimbaran." },
      { day: "Day 6", title: "Departure", text: "Breakfast, late checkout and airport transfer." },
    ],
  },
  {
    id: "santorini-sunsets",
    title: "Santorini Sunsets",
    destinationId: "santorini",
    location: "Oia & Fira, Greece",
    category: "Beach",
    price: 108360,
    oldPrice: 1450,
    days: 5,
    nights: 4,
    groupSize: "Max 10 travellers",
    rating: 4.9,
    reviews: 168,
    image: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1504512485720-7d83a16ee930?auto=format&fit=crop&w=1200&q=80",
    ],
    summary:
      "Four slow nights on the caldera rim with a catamaran day, a winery tasting and the best sunset seat in Oia reserved for you.",
    includes: ["4 nights cave-house hotel", "Daily breakfast", "Catamaran cruise with lunch", "Winery tasting tour", "Airport transfers"],
    excludes: ["Flights", "Travel insurance", "Most dinners", "Optional ATV rental"],
    itinerary: [
      { day: "Day 1", title: "Arrival in Fira", text: "Transfer to your cave house and an evening caldera walk." },
      { day: "Day 2", title: "Catamaran day", text: "Sail past Red Beach and the hot springs with lunch on board." },
      { day: "Day 3", title: "Villages & wine", text: "Pyrgos and Megalochori, then an Assyrtiko tasting at a family winery." },
      { day: "Day 4", title: "Oia sunset", text: "Free morning, afternoon in Ammoudi Bay and a reserved sunset table." },
      { day: "Day 5", title: "Departure", text: "Breakfast and airport transfer." },
    ],
  },
  {
    id: "kyoto-heritage",
    title: "Kyoto Heritage Trail",
    destinationId: "kyoto",
    location: "Kyoto, Nara & Osaka, Japan",
    category: "Cultural",
    price: 130200,
    oldPrice: 1720,
    days: 7,
    nights: 6,
    groupSize: "Max 14 travellers",
    rating: 4.9,
    reviews: 302,
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?auto=format&fit=crop&w=1200&q=80",
    ],
    summary:
      "A week of temples, tea and trains — Fushimi Inari at dawn, Arashiyama bamboo, a Nara day trip and Osaka's street-food alleys.",
    includes: ["6 nights 4-star hotels", "Daily breakfast", "7-day regional rail pass", "Tea ceremony", "Guided Nara day trip", "Airport transfers"],
    excludes: ["International flights", "Travel insurance", "Dinners", "Luggage forwarding"],
    itinerary: [
      { day: "Day 1", title: "Arrival in Kyoto", text: "Transfer from Kansai, evening stroll along Pontocho Alley." },
      { day: "Day 2", title: "Eastern Kyoto", text: "Kiyomizu-dera, Gion lanes and a traditional tea ceremony." },
      { day: "Day 3", title: "Fushimi Inari at dawn", text: "Early torii-gate climb before the crowds, afternoon at Tofuku-ji." },
      { day: "Day 4", title: "Arashiyama", text: "Bamboo grove, monkey park and a Hozugawa river boat." },
      { day: "Day 5", title: "Nara day trip", text: "Todai-ji's Great Buddha, deer park and Kasuga shrine lanterns." },
      { day: "Day 6", title: "Osaka", text: "Dotonbori food walk and Osaka Castle grounds." },
      { day: "Day 7", title: "Departure", text: "Free morning and airport transfer." },
    ],
  },
  {
    id: "alpine-rail",
    title: "Alpine Rail Journey",
    destinationId: "swiss-alps",
    location: "Lucerne, Interlaken & Zermatt",
    category: "Mountain",
    price: 149520,
    oldPrice: 1990,
    days: 6,
    nights: 5,
    groupSize: "Max 16 travellers",
    rating: 4.7,
    reviews: 141,
    image: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1527668752968-14dc70a27c95?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80",
    ],
    summary:
      "Panoramic trains from Lake Lucerne to the Matterhorn, with a Jungfraujoch excursion and time to hike between the rides.",
    includes: ["5 nights 4-star hotels", "Daily breakfast", "Swiss Travel Pass", "Jungfraujoch excursion", "Gornergrat railway ticket"],
    excludes: ["Flights", "Travel insurance", "Lunches and dinners", "Cable-car extras"],
    itinerary: [
      { day: "Day 1", title: "Arrival in Lucerne", text: "Chapel Bridge, old-town walk and a lake cruise at dusk." },
      { day: "Day 2", title: "Mount Pilatus", text: "Cogwheel railway up, cable car down, free afternoon." },
      { day: "Day 3", title: "To Interlaken", text: "Scenic rail transfer and an evening between the two lakes." },
      { day: "Day 4", title: "Jungfraujoch", text: "Top of Europe excursion, ice palace and glacier viewpoint." },
      { day: "Day 5", title: "Zermatt & Gornergrat", text: "Glacier Express leg, then the Gornergrat railway for Matterhorn views." },
      { day: "Day 6", title: "Departure", text: "Morning train to Zurich airport." },
    ],
  },
  {
    id: "sahara-nights",
    title: "Marrakech & Sahara Nights",
    destinationId: "marrakech",
    location: "Marrakech & Agafay, Morocco",
    category: "Cultural",
    price: 62160,
    oldPrice: 890,
    days: 5,
    nights: 4,
    groupSize: "Max 12 travellers",
    rating: 4.6,
    reviews: 187,
    image: "https://images.unsplash.com/photo-1597212618440-806262de4f6b?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1597212618440-806262de4f6b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1539020140153-e479b8c22e70?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1518990708123-2c1b8b0c3a83?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1489493887464-892be6d1daae?auto=format&fit=crop&w=1200&q=80",
    ],
    summary:
      "Riad mornings and medina markets, a High Atlas valley day and one night under canvas in the Agafay desert.",
    includes: ["3 nights riad + 1 desert camp", "Daily breakfast", "Guided medina tour", "Atlas Mountains day trip", "Camel ride & desert dinner"],
    excludes: ["Flights", "Travel insurance", "City lunches", "Hammam treatments"],
    itinerary: [
      { day: "Day 1", title: "Arrival", text: "Riad check-in and a rooftop dinner over Jemaa el-Fnaa." },
      { day: "Day 2", title: "Medina & palaces", text: "Bahia Palace, Saadian Tombs and guided souk navigation." },
      { day: "Day 3", title: "Atlas Mountains", text: "Ourika Valley waterfalls and a Berber family lunch." },
      { day: "Day 4", title: "Agafay desert", text: "Camel ride, dune sunset, dinner and drumming at camp." },
      { day: "Day 5", title: "Departure", text: "Return to Marrakech and airport transfer." },
    ],
  },
  {
    id: "serengeti-safari",
    title: "Serengeti Migration Safari",
    destinationId: "serengeti",
    location: "Serengeti & Ngorongoro, Tanzania",
    category: "Wildlife",
    price: 205800,
    oldPrice: 2780,
    days: 8,
    nights: 7,
    groupSize: "Max 6 per vehicle",
    rating: 4.9,
    reviews: 96,
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1547970810-dc1eac37d174?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&w=1200&q=80",
    ],
    summary:
      "Seven nights tracking the Great Migration with expert guides, tented camps on the plains and a Ngorongoro crater descent.",
    includes: ["7 nights lodges & tented camps", "All meals on safari", "Private 4x4 with guide", "Park and crater fees", "Arusha airport transfers"],
    excludes: ["International flights", "Visas", "Balloon safari", "Tips and drinks"],
    itinerary: [
      { day: "Day 1", title: "Arrive Arusha", text: "Lodge night and safari briefing." },
      { day: "Day 2", title: "Tarangire", text: "Elephant herds and baobab plains, night at a tented camp." },
      { day: "Day 3-5", title: "Central Serengeti", text: "Full game drives tracking big cats and the migration herds." },
      { day: "Day 6", title: "Northern Serengeti", text: "Mara River crossings in season, sundowners on the kopjes." },
      { day: "Day 7", title: "Ngorongoro Crater", text: "Descent into the caldera for rhino, lion and flamingo sightings." },
      { day: "Day 8", title: "Departure", text: "Drive to Arusha and flight home." },
    ],
  },
  {
    id: "iceland-ring",
    title: "Iceland Fire & Ice",
    destinationId: "iceland",
    location: "Reykjavik & South Coast",
    category: "Adventure",
    price: 136080,
    oldPrice: 1840,
    days: 6,
    nights: 5,
    groupSize: "Max 14 travellers",
    rating: 4.8,
    reviews: 158,
    image: "https://images.unsplash.com/photo-1504829857797-ddff29c27927?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1504829857797-ddff29c27927?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1476610182048-b716b8518aae?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1490077476659-095159692ab5?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1520769945061-0a448c463865?auto=format&fit=crop&w=1200&q=80",
    ],
    summary:
      "Waterfalls, glacier lagoons and an ice-cave walk, finishing with aurora hunts away from the city lights.",
    includes: ["5 nights hotels & guesthouses", "Daily breakfast", "Golden Circle tour", "Glacier ice-cave walk", "Northern lights hunt", "Blue Lagoon entry"],
    excludes: ["Flights", "Travel insurance", "Lunches and dinners", "Snowmobile add-on"],
    itinerary: [
      { day: "Day 1", title: "Arrival", text: "Blue Lagoon soak en route to Reykjavik." },
      { day: "Day 2", title: "Golden Circle", text: "Thingvellir rift, Geysir and Gullfoss." },
      { day: "Day 3", title: "South Coast", text: "Seljalandsfoss, Skogafoss and Reynisfjara black sands." },
      { day: "Day 4", title: "Glacier day", text: "Jokulsarlon lagoon, Diamond Beach and an ice-cave walk." },
      { day: "Day 5", title: "Aurora night", text: "Snaefellsnes coast by day, northern lights hunt after dark." },
      { day: "Day 6", title: "Departure", text: "Reykjavik morning and airport transfer." },
    ],
  },
  {
    id: "maldives-reef",
    title: "Maldives Reef Retreat",
    destinationId: "maldives",
    location: "North Male Atoll, Maldives",
    category: "Beach",
    price: 176400,
    oldPrice: 2390,
    days: 5,
    nights: 4,
    groupSize: "Couples & small groups",
    rating: 4.9,
    reviews: 122,
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1540202404-a2f29016b523?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80",
    ],
    summary:
      "Four nights in an overwater villa with house-reef snorkelling, a sandbank picnic and a sunset dolphin cruise.",
    includes: ["4 nights overwater villa", "Half board", "Speedboat transfers", "Snorkelling gear", "Sandbank picnic", "Dolphin cruise"],
    excludes: ["Flights", "Travel insurance", "Diving courses", "Spa treatments"],
    itinerary: [
      { day: "Day 1", title: "Arrival", text: "Speedboat to the resort and a sunset welcome drink." },
      { day: "Day 2", title: "House reef", text: "Guided snorkel and a free afternoon on the villa deck." },
      { day: "Day 3", title: "Sandbank picnic", text: "Private sandbank lunch and an evening dolphin cruise." },
      { day: "Day 4", title: "Atoll hopping", text: "Local island visit and a sunset fishing trip." },
      { day: "Day 5", title: "Departure", text: "Breakfast and speedboat back to Male." },
    ],
  },
  {
    id: "patagonia-trek",
    title: "Patagonia W Trek",
    destinationId: "patagonia",
    location: "Torres del Paine, Chile",
    category: "Adventure",
    price: 166320,
    oldPrice: 2240,
    days: 9,
    nights: 8,
    groupSize: "Max 10 trekkers",
    rating: 4.7,
    reviews: 78,
    image: "https://images.unsplash.com/photo-1478827387698-1527781a4887?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1478827387698-1527781a4887?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1526772662000-3f88f10405ff?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1454391304352-2bf4678b1a7a?auto=format&fit=crop&w=1200&q=80",
    ],
    summary:
      "The classic W circuit with a mountain guide, refugio nights and a boat crossing to Grey Glacier.",
    includes: ["8 nights refugios & hotels", "All trek meals", "Certified mountain guide", "Park entry", "Grey Glacier boat", "Punta Arenas transfers"],
    excludes: ["Flights", "Trekking gear rental", "Travel insurance", "Tips"],
    itinerary: [
      { day: "Day 1-2", title: "Punta Arenas to Puerto Natales", text: "Gear check, briefing and the drive north." },
      { day: "Day 3", title: "Base of the Towers", text: "Steep climb to the Torres viewpoint." },
      { day: "Day 4-5", title: "French Valley", text: "Los Cuernos traverse and the valley lookout." },
      { day: "Day 6-7", title: "Grey Glacier", text: "Glacier boat, hanging bridges and ice viewpoints." },
      { day: "Day 8-9", title: "Return", text: "Back to Puerto Natales, celebration dinner and departure." },
    ],
  },
  {
    id: "rome-classics",
    title: "Rome Classics Weekend",
    destinationId: "rome",
    location: "Rome, Italy",
    category: "Cultural",
    price: 82320,
    oldPrice: 1120,
    days: 5,
    nights: 4,
    groupSize: "Max 16 travellers",
    rating: 4.6,
    reviews: 245,
    image: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1531572753322-ad063cecc140?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1529260830199-42c24126f198?auto=format&fit=crop&w=1200&q=80",
    ],
    summary:
      "Skip-the-line Colosseum and Vatican mornings paired with a Trastevere food walk and a day trip to Tivoli.",
    includes: ["4 nights central hotel", "Daily breakfast", "Colosseum & Forum tour", "Early-entry Vatican tour", "Trastevere food walk"],
    excludes: ["Flights", "Travel insurance", "Most meals", "City tax"],
    itinerary: [
      { day: "Day 1", title: "Arrival", text: "Check-in near Piazza Navona and an evening passeggiata." },
      { day: "Day 2", title: "Ancient Rome", text: "Colosseum, Roman Forum and Palatine Hill with a guide." },
      { day: "Day 3", title: "Vatican morning", text: "Early-entry Sistine Chapel and St Peter's dome climb." },
      { day: "Day 4", title: "Tivoli day trip", text: "Villa d'Este gardens and Hadrian's Villa." },
      { day: "Day 5", title: "Departure", text: "Espresso, last piazza and transfer to Fiumicino." },
    ],
  },
];

const TESTIMONIALS = [
  {
    name: "Aarti Menon",
    trip: "Kyoto Heritage Trail",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80",
    text: "Every transfer, temple ticket and dinner booking was handled. We just turned up and enjoyed Japan.",
  },
  {
    name: "Daniel Okafor",
    trip: "Serengeti Migration Safari",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
    text: "Our guide found a river crossing on day four. Eight days later we were still talking about it.",
  },
  {
    name: "Lena Brandt",
    trip: "Iceland Fire & Ice",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=200&q=80",
    text: "The aurora night was rescheduled twice for cloud cover — and we still saw it. That's proper planning.",
  },
];

const TEAM = [
  { name: "Priya Raghavan", role: "Founder & Trip Designer", img: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=500&q=80" },
  { name: "Marcus Hale", role: "Head of Operations", img: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=500&q=80" },
  { name: "Sofia Almeida", role: "Adventure Specialist", img: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=500&q=80" },
  { name: "Kenji Watanabe", role: "Asia Programme Lead", img: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=500&q=80" },
];

const CATEGORIES = ["All", "Beach", "Mountain", "Cultural", "Adventure", "Wildlife"];
