/* Nestora India — property + people data (vanilla JS) */
window.NESTORA_PROPERTIES = [
  {
    id: "prop-1",
    title: "Palm Grove Sea-View Villa",
    city: "Mumbai",
    locality: "Juhu, Mumbai, Maharashtra",
    type: "Villa",
    price: 125000000,
    priceLabel: "₹12.50 Cr",
    beds: 4,
    baths: 5,
    area: "4,250 sq.ft.",
    tag: "Ready to Move",
    rera: "P51800012345",
    desc: "A sunlit four-bedroom villa a short walk from Juhu beach, with a private lawn and staff quarters.",
    img: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=70",
  },
  {
    id: "prop-2",
    title: "Prestige Skyline Residences",
    city: "Bengaluru",
    locality: "Whitefield, Bengaluru, Karnataka",
    type: "Apartment",
    price: 21500000,
    priceLabel: "₹2.15 Cr",
    beds: 3,
    baths: 3,
    area: "1,860 sq.ft.",
    tag: "New Launch",
    rera: "PRM/KA/RERA/1251/446",
    desc: "Three-bedroom smart homes in a gated tower with clubhouse, lap pool and EV-ready parking.",
    img: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=70",
  },
  {
    id: "prop-3",
    title: "Hillview Heritage Bungalow",
    city: "Pune",
    locality: "Koregaon Park, Pune, Maharashtra",
    type: "Bungalow",
    price: 89000000,
    priceLabel: "₹8.90 Cr",
    beds: 5,
    baths: 4,
    area: "5,600 sq.ft.",
    tag: "Resale",
    rera: "P52100028841",
    desc: "A restored 1940s bungalow on a leafy plot, with original teak joinery and a courtyard.",
    img: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=70",
  },
  {
    id: "prop-4",
    title: "Cyber Green Sky Suites",
    city: "Gurugram",
    locality: "Golf Course Road, Gurugram, Haryana",
    type: "Apartment",
    price: 34500000,
    priceLabel: "₹3.45 Cr",
    beds: 3,
    baths: 4,
    area: "2,410 sq.ft.",
    tag: "Ready to Move",
    rera: "HRERA-GGM-482-2023",
    desc: "High-floor suites overlooking the Aravallis, minutes from Cyber Hub and the metro.",
    img: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=70",
  },
  {
    id: "prop-5",
    title: "Charminar View Apartments",
    city: "Hyderabad",
    locality: "Banjara Hills, Hyderabad, Telangana",
    type: "Apartment",
    price: 14800000,
    priceLabel: "₹1.48 Cr",
    beds: 2,
    baths: 2,
    area: "1,320 sq.ft.",
    tag: "Ready to Move",
    rera: "P02400004512",
    desc: "Compact two-bedroom homes in a quiet Banjara Hills lane, close to schools and hospitals.",
    img: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=70",
  },
  {
    id: "prop-6",
    title: "Backwater Retreat Cottage",
    city: "Kochi",
    locality: "Kumbalangi, Kochi, Kerala",
    type: "Villa",
    price: 9600000,
    priceLabel: "₹96 Lakh",
    beds: 3,
    baths: 3,
    area: "2,050 sq.ft.",
    tag: "Holiday Home",
    rera: "K-RERA/PRJ/ERN/0912",
    desc: "A laterite-and-teak cottage on the backwaters, with a jetty and a shaded verandah.",
    img: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=70",
  },
  {
    id: "prop-7",
    title: "Marina Bay Duplex",
    city: "Chennai",
    locality: "Besant Nagar, Chennai, Tamil Nadu",
    type: "Duplex",
    price: 42000000,
    priceLabel: "₹4.20 Cr",
    beds: 4,
    baths: 4,
    area: "3,150 sq.ft.",
    tag: "Ready to Move",
    rera: "TN/29/Building/0345/2023",
    desc: "A breezy sea-facing duplex with double-height living and a rooftop deck.",
    img: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=70",
  },
  {
    id: "prop-8",
    title: "Salt Lake Garden Flats",
    city: "Kolkata",
    locality: "Salt Lake Sector V, Kolkata, West Bengal",
    type: "Apartment",
    price: 7900000,
    priceLabel: "₹79 Lakh",
    beds: 2,
    baths: 2,
    area: "1,105 sq.ft.",
    tag: "New Launch",
    rera: "WBRERA/P/KOL/2024/000221",
    desc: "Value-priced two-bedroom flats beside the IT corridor, with a landscaped podium garden.",
    img: "https://images.unsplash.com/photo-1567496898669-ee935f5f647a?auto=format&fit=crop&w=1200&q=70",
  },
  {
    id: "prop-9",
    title: "Aravalli Ridge Plots",
    city: "Jaipur",
    locality: "Jagatpura, Jaipur, Rajasthan",
    type: "Plot",
    price: 5400000,
    priceLabel: "₹54 Lakh",
    beds: 0,
    baths: 0,
    area: "2,400 sq.ft.",
    tag: "Investment",
    rera: "RAJ/P/2024/2712",
    desc: "Sanctioned residential plots on the ring road, ideal for a build-to-own home.",
    img: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=70",
  },
];

window.NESTORA_TESTIMONIALS = [
  {
    name: "Meera Iyer",
    place: "Bengaluru, Karnataka",
    text: "Nestora handled everything from the site visits to the RERA paperwork. We moved into our Whitefield home in eleven weeks.",
  },
  {
    name: "Arjun Malhotra",
    place: "Gurugram, Haryana",
    text: "They talked me out of two overpriced towers before finding the right one. That honesty is rare in this market.",
  },
  {
    name: "Sneha Kulkarni",
    place: "Pune, Maharashtra",
    text: "The team negotiated ₹18 lakh off the quoted price and arranged the home loan sanction in the same week.",
  },
  {
    name: "Rahul Nair",
    place: "Kochi, Kerala",
    text: "I bought our backwater cottage entirely over video calls from Dubai. Every document arrived exactly when promised.",
  },
  {
    name: "Farhan Qureshi",
    place: "Hyderabad, Telangana",
    text: "Clear title checks, honest pricing and no chasing. Nestora made our first purchase far less frightening.",
  },
  {
    name: "Ananya Sen",
    place: "Kolkata, West Bengal",
    text: "Their rental management team has kept our Salt Lake flat occupied for three straight years without a single dispute.",
  },
];

window.NESTORA_AGENTS = [
  {
    name: "Vikram Rao",
    role: "Principal Advisor, Mumbai",
    deals: "410+ deals",
    years: "14 years",
    img: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=70",
  },
  {
    name: "Priyanka Deshmukh",
    role: "Head of Residential, Pune",
    deals: "330+ deals",
    years: "11 years",
    img: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=70",
  },
  {
    name: "Harish Menon",
    role: "Investment Lead, Bengaluru",
    deals: "290+ deals",
    years: "9 years",
    img: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=800&q=70",
  },
];
