/* Vanveda catalogue + journal content (plain JS, no build step) */
window.VANVEDA_PRODUCTS = [
  {
    id: "neem-cleanser",
    name: "Nimba Purifying Cleanser",
    category: "Cleansers",
    price: 749,
    mrp: 899,
    size: "200 ml",
    img: "/images/p-cleanser.jpg",
    tag: "Bestseller",
    blurb: "A gentle gel wash with cold-pressed neem and Salem turmeric for clear, calm skin.",
    ingredients: ["Neem leaf extract", "Salem turmeric", "Aloe vera juice", "Vetiver water"],
    ritual: ["Massage on damp skin for 30 seconds", "Rinse with lukewarm water", "Use morning and night"],
  },
  {
    id: "kumkumadi-serum",
    name: "Kumkumadi Glow Serum",
    category: "Serums",
    price: 1450,
    size: "30 ml",
    img: "/images/p-serum.jpg",
    tag: "Top pick",
    blurb: "The classic Kerala glow oil-serum, reformulated light — saffron, manjistha and sesame.",
    ingredients: ["Kashmiri saffron", "Manjistha root", "Cold-pressed sesame", "Lotus extract"],
    ritual: ["Warm 3 drops between palms", "Press into cleansed skin", "Follow with moisturiser"],
  },
  {
    id: "rose-cream",
    name: "Gulab Rejuvenating Cream",
    category: "Moisturisers",
    price: 1290,
    mrp: 1490,
    size: "50 g",
    img: "/images/p-cream.jpg",
    tag: "20% off",
    blurb: "Whipped moisturiser with Pushkar rose water and ashwagandha for overnight repair.",
    ingredients: ["Pushkar rose water", "Ashwagandha", "Shea butter", "Kokum butter"],
    ritual: ["Take a pea-sized amount", "Press upward over face and neck", "Best used at night"],
  },
  {
    id: "kesha-oil",
    name: "Kesha Hair & Body Oil",
    category: "Body & Hair",
    price: 890,
    size: "200 ml",
    img: "/images/p-oil.jpg",
    blurb: "A 12-herb infused oil for champi rituals — bhringraj, amla and curry leaf.",
    ingredients: ["Bhringraj", "Amla", "Curry leaf", "Virgin coconut oil"],
    ritual: ["Warm slightly", "Massage into scalp and body", "Leave 45 minutes, then wash"],
  },
  {
    id: "clay-mask",
    name: "Multani Detox Clay Mask",
    category: "Masks",
    price: 690,
    size: "100 g",
    img: "/images/p-mask.jpg",
    tag: "New",
    blurb: "Rajasthani multani mitti with tulsi and vetiver to draw out congestion.",
    ingredients: ["Multani mitti", "Tulsi", "Vetiver", "Sandalwood powder"],
    ritual: ["Mix 1 tsp with rose water", "Apply an even layer for 10 minutes", "Rinse gently"],
  },
  {
    id: "kajal-kohl",
    name: "Kohl Kajal Stick",
    category: "Makeup",
    price: 520,
    size: "3 g",
    img: "/images/p-makeup.jpg",
    blurb: "Smudge-proof intense black kajal, ghee-conditioned and ophthalmologist tested.",
    ingredients: ["Almond oil", "Camphor", "Castor wax", "Natural carbon black"],
    ritual: ["Line the inner rim", "Smudge with fingertip for a soft kohl look"],
  },
  {
    id: "terracotta-tint",
    name: "Terracotta Lip & Cheek Tint",
    category: "Makeup",
    price: 640,
    size: "5 g",
    img: "/images/p-makeup.jpg",
    blurb: "A sheer clay-toned balm tint pigmented with beetroot and alkanet root.",
    ingredients: ["Beetroot extract", "Alkanet root", "Kokum butter", "Vitamin E"],
    ritual: ["Dab on lips and cheeks", "Blend with fingertips", "Build for depth"],
  },
  {
    id: "vetiver-mist",
    name: "Vetiver Cooling Face Mist",
    category: "Toners",
    price: 580,
    size: "100 ml",
    img: "/images/p-serum.jpg",
    blurb: "Steam-distilled khus water to reset skin through Indian summers.",
    ingredients: ["Vetiver (khus) water", "Rose water", "Glycerin", "Aloe"],
    ritual: ["Spritz over face any time of day", "Pat in gently"],
  },
  {
    id: "ubtan-scrub",
    name: "Haldi Ubtan Polishing Scrub",
    category: "Masks",
    price: 720,
    size: "150 g",
    img: "/images/p-mask.jpg",
    blurb: "The bridal ubtan recipe — chickpea flour, turmeric and raw honey granules.",
    ingredients: ["Chickpea flour", "Turmeric", "Honey granules", "Sandalwood"],
    ritual: ["Mix with milk or curd", "Massage in circles", "Rinse after 5 minutes"],
  },
  {
    id: "amla-shampoo",
    name: "Amla Reetha Hair Cleanser",
    category: "Body & Hair",
    price: 810,
    size: "250 ml",
    img: "/images/p-cleanser.jpg",
    blurb: "Sulphate-free wash built on the traditional amla-reetha-shikakai trio.",
    ingredients: ["Amla", "Reetha", "Shikakai", "Hibiscus"],
    ritual: ["Lather on wet hair", "Focus on the scalp", "Rinse thoroughly"],
  },
  {
    id: "chandan-sunscreen",
    name: "Chandan Mineral Sunscreen SPF 50",
    category: "Moisturisers",
    price: 990,
    size: "50 ml",
    img: "/images/p-cream.jpg",
    tag: "Bestseller",
    blurb: "Non-white-cast mineral SPF with Mysore sandalwood and zinc oxide.",
    ingredients: ["Zinc oxide 18%", "Mysore sandalwood", "Squalane", "Green tea"],
    ritual: ["Apply two finger-lengths as the last step", "Reapply every 3 hours outdoors"],
  },
  {
    id: "ritual-set",
    name: "The Complete Dinacharya Set",
    category: "Sets",
    price: 3490,
    mrp: 4130,
    size: "4 products",
    img: "/images/p-serum.jpg",
    tag: "Save ₹640",
    blurb: "Cleanser, serum, cream and mist — a full morning-to-night Ayurvedic routine.",
    ingredients: ["Nimba Cleanser", "Kumkumadi Serum", "Gulab Cream", "Vetiver Mist"],
    ritual: ["Cleanse", "Serum", "Moisturise", "Mist through the day"],
  },
];

window.VANVEDA_JOURNAL = [
  {
    title: "Dinacharya: building an Ayurvedic day",
    date: "12 Aug 2026",
    read: "6 min",
    img: "/images/story.jpg",
    excerpt: "How the classical daily routine translates into a modern skincare ritual you can actually keep.",
  },
  {
    title: "Why kumkumadi still works after 500 years",
    date: "28 Jul 2026",
    read: "5 min",
    img: "/images/p-serum.jpg",
    excerpt: "Saffron, manjistha and sesame — a look at the botanical actives behind India's most loved glow oil.",
  },
  {
    title: "The truth about multani mitti",
    date: "09 Jul 2026",
    read: "4 min",
    img: "/images/p-mask.jpg",
    excerpt: "Clay is brilliant, but over-masking is not. Here is how often your skin actually wants it.",
  },
  {
    title: "Champi: the Sunday oiling ritual",
    date: "21 Jun 2026",
    read: "7 min",
    img: "/images/p-oil.jpg",
    excerpt: "A step-by-step scalp massage, from oil temperature to the pressure points that matter.",
  },
  {
    title: "Kajal, minus the irritation",
    date: "02 Jun 2026",
    read: "3 min",
    img: "/images/p-makeup.jpg",
    excerpt: "What to look for on a kajal label if you wear contact lenses or have sensitive eyes.",
  },
  {
    title: "Sunscreen for Indian skin tones",
    date: "18 May 2026",
    read: "5 min",
    img: "/images/p-cream.jpg",
    excerpt: "Mineral filters have come a long way. No grey cast, no pilling, still SPF 50.",
  },
];
